### ISSUE TITLE
Reordering of Lower Rows in Long Table View

### ISSUE THREAD

**Issue by oskirkon** [adamshin/SwiftReorder#28]
I encountered a bug where when long pressing a row that appeared towards the bottom of a longer table view (after scrolling to reach the row) would have no effect. I took some steps to diagnose.

Steps to Reproduce:

1) Create table views with 30ish rows, containing simple text.
2) Scroll to bottom of table view.
3) Try to select bottom row to reorder.
4) Nothing will happen

Setting breakpoints shows the gesture recognizer is triggered. The reordering process stops on line 33 of ReorderController.swift: `guard let cell = tableView.cellForRow(at: indexPath) else { return }`

The cell is nil, even though the cell is clearly visible on the screen. Further diagnosis shows that calling: `tableView.indexPathsForVisibleRows` reveals that the index path for the selected row does not appear in the list, even though the cell is visible (leading me to suspect this is a UIKit bug, which occurs for a short time after `tableView.reloadData()` is called.

Removing the `tableView.reloadData()` from line 31 of ReorderController.swift seems to resolve the issue, but am unsure what side effects this may cause.

**Comment by Mimo191** [comment]
Hi, I encountered the same bug and didn't found a solution other the one you suggested.

But by commenting the line: `tableView.reloadData()`, you wont have the same effect when the reorder is triggered. I mean the dragged cell background color is not white, but grayed a little bit due to cell highlighting.

I suggest adding this line: `tableView.reloadRows(at: [indexPath], with: .fade)`

Apart from that, I think it's a great library, thanks to all the contributors.

**Comment by laxmorek** [comment]
@adamshin This issue can be closed referring to merged #39
